INSERT INTO USERS (ID, NAME, USERNAME, PASSWORD, ENABLED) VALUES (1, 'Giovanny Granda', 'ggranda', '$2a$10$DzXXpW6FJqiP2zjLgshb6OtqtRGVc5FOYaasP6c7oq9EJ/Yqk6YKe', TRUE)
INSERT INTO USERS (ID, NAME, USERNAME, PASSWORD, ENABLED) VALUES (2, 'Nicholas Cage', 'user', '$2a$10$oRWPnV0ugIQMzAFksOESOureo/mwCtYnB93.fRc.joF7Wu0w7l5w.', TRUE)

INSERT INTO AUTHORITIES (ID, NAME) VALUES (1, 'ROLE_ADMIN')
INSERT INTO AUTHORITIES (ID, NAME) VALUES (2, 'ROLE_USER')

INSERT INTO USERS_AUTHORITIES (USERS_ID, AUTHORITIES_ID) VALUES (1, 1)
INSERT INTO USERS_AUTHORITIES (USERS_ID, AUTHORITIES_ID) VALUES (2, 2)
