CREATE TABLE USERS (
id INT PRIMARY KEY,
name VARCHAR(100),
username VARCHAR(100),
password VARCHAR(255),
enabled BOOLEAN
);

CREATE TABLE AUTHORITIES (
id INT PRIMARY KEY,
name VARCHAR(100)
);

CREATE TABLE USERS_AUTHORITIES(
users_id INT,
authorities_id INT
);